-- ============================================================
-- Customer & Commercial Analytics | SQL Solutions
-- Dataset: E-Commerce Customer Behavior Dataset V2
-- Tool: MySQL Workbench
-- Table: ecommerce_customer_data
-- ============================================================


-- ============================================================
-- Q1. Customer Count
-- Find the total number of unique customers.
-- ============================================================

SELECT COUNT(DISTINCT Customer_ID) AS total_customers
FROM ecommerce_customer_data;


-- ============================================================
-- Q2. Total Orders
-- Find the total number of unique orders.
-- ============================================================

SELECT COUNT(DISTINCT Order_ID) AS total_orders
FROM ecommerce_customer_data;


-- ============================================================
-- Q3. Total Revenue
-- Calculate the total revenue using Total_Amount.
-- ============================================================

SELECT SUM(Total_Amount) AS total_revenue
FROM ecommerce_customer_data;


-- ============================================================
-- Q4. Revenue by Product Category
-- Find total revenue and total quantity sold for each category.
-- ============================================================

SELECT
    Product_Category,
    SUM(Quantity) AS total_quantity,
    SUM(Total_Amount) AS total_revenue
FROM ecommerce_customer_data
GROUP BY Product_Category;


-- ============================================================
-- Q5. Top 10 Customers by Revenue
-- Find the 10 customers who generated the highest total revenue.
-- ============================================================

SELECT
    Customer_ID,
    SUM(Total_Amount) AS total_customer_revenue
FROM ecommerce_customer_data
GROUP BY Customer_ID
ORDER BY total_customer_revenue DESC
LIMIT 10;


-- ============================================================
-- Q6. Average Order Value
-- Calculate the average order value.
-- AOV = Total Revenue / Number of Orders
-- ============================================================

SELECT
    SUM(Total_Amount) / COUNT(DISTINCT Order_ID) AS avg_order_value
FROM ecommerce_customer_data;


-- ============================================================
-- Q7. Returning vs Non-Returning Customers
-- Compare total revenue generated by returning and non-returning
-- customers.
-- ============================================================

SELECT
    Is_Returning_Customer,
    SUM(Total_Amount) AS total_revenue
FROM ecommerce_customer_data
GROUP BY Is_Returning_Customer;


-- ============================================================
-- Q8. Customer Purchase Frequency
-- Find customers with more than 3 orders.
-- ============================================================

SELECT
    Customer_ID,
    COUNT(DISTINCT Order_ID) AS total_number_of_orders
FROM ecommerce_customer_data
GROUP BY Customer_ID
HAVING COUNT(DISTINCT Order_ID) > 3;


-- ============================================================
-- Q9. Top Customer Within Each City
-- Find the highest-revenue customer in every city.
-- ============================================================

WITH TABLE_1 AS (
    SELECT
        Customer_ID,
        City,
        SUM(Total_Amount) AS total_revenue,
        ROW_NUMBER() OVER (
            PARTITION BY City
            ORDER BY SUM(Total_Amount) DESC
        ) AS rnk
    FROM ecommerce_customer_data
    GROUP BY Customer_ID, City
)
SELECT
    Customer_ID,
    City,
    total_revenue,
    rnk
FROM TABLE_1
WHERE rnk = 1;


-- ============================================================
-- Q10. First and Latest Purchase
-- For every customer, find first purchase date, latest purchase
-- date, number of orders, and total revenue.
-- ============================================================

SELECT
    Customer_ID,
    COUNT(DISTINCT Order_ID) AS total_orders,
    MIN(Date) AS first_purchase_date,
    MAX(Date) AS latest_purchase_date,
    SUM(Total_Amount) AS revenue
FROM ecommerce_customer_data
GROUP BY Customer_ID;


-- ============================================================
-- Q11. Days Between Customer Purchases
-- Calculate the number of days between each customer's current
-- purchase and previous purchase.
-- ============================================================

WITH TABLE_1 AS (
    SELECT
        Customer_ID,
        Date AS current_purchase,
        LAG(Date) OVER (
            PARTITION BY Customer_ID
            ORDER BY Date
        ) AS previous_purchase
    FROM ecommerce_customer_data
),
TABLE_2 AS (
    SELECT
        Customer_ID,
        current_purchase,
        previous_purchase,
        DATEDIFF(current_purchase, previous_purchase) AS difference
    FROM TABLE_1
)
SELECT *
FROM TABLE_2;


-- ============================================================
-- Q12. Discount Impact
-- Compare revenue and AOV for orders with and without discounts.
-- Also calculate total discount given.
-- ============================================================

SELECT
    SUM(
        CASE
            WHEN Discount_Amount > 0 THEN Total_Amount
            ELSE 0
        END
    ) AS revenue_with_discount,

    SUM(
        CASE
            WHEN Discount_Amount > 0 THEN Total_Amount
            ELSE 0
        END
    )
    / COUNT(DISTINCT
        CASE
            WHEN Discount_Amount > 0 THEN Order_ID
        END
    ) AS aov_with_discount,

    SUM(Discount_Amount) AS total_discount_given,

    SUM(
        CASE
            WHEN Discount_Amount = 0 THEN Total_Amount
            ELSE 0
        END
    ) AS revenue_without_discount,

    SUM(
        CASE
            WHEN Discount_Amount = 0 THEN Total_Amount
            ELSE 0
        END
    )
    / COUNT(DISTINCT
        CASE
            WHEN Discount_Amount = 0 THEN Order_ID
        END
    ) AS aov_without_discount

FROM ecommerce_customer_data;


-- ============================================================
-- Q13. Discount by Category
-- For each product category, calculate total discount, total
-- revenue, and average discount per order.
-- ============================================================

SELECT
    Product_Category,
    SUM(Total_Amount) AS total_revenue,
    SUM(Discount_Amount) AS total_discount,

    SUM(
        CASE
            WHEN Discount_Amount > 0 THEN Discount_Amount
            ELSE 0
        END
    )
    /
    COUNT(
        DISTINCT CASE
            WHEN Discount_Amount > 0 THEN Order_ID
        END
    ) AS avg_discount_per_order

FROM ecommerce_customer_data
GROUP BY Product_Category;


-- ============================================================
-- Q14. Top 5 Categories by Revenue
-- Rank product categories by total revenue and return the top 5.
-- ============================================================

WITH ranked_categories AS (
    SELECT
        Product_Category,
        SUM(Total_Amount) AS Revenue,
        ROW_NUMBER() OVER (
            ORDER BY SUM(Total_Amount) DESC
        ) AS rnk
    FROM ecommerce_customer_data
    GROUP BY Product_Category
)
SELECT
    Product_Category,
    Revenue,
    rnk
FROM ranked_categories
WHERE rnk <= 5;


-- ============================================================
-- Q15. Delivery Time vs Customer Rating
-- Calculate average customer rating for each delivery-time bucket.
-- ============================================================

SELECT
    CASE
        WHEN Delivery_Time_Days BETWEEN 1 AND 3 THEN '1-3 days'
        WHEN Delivery_Time_Days BETWEEN 4 AND 7 THEN '4-7 days'
        WHEN Delivery_Time_Days >= 8 THEN '8+ days'
    END AS delivery_bucket,

    AVG(Customer_Rating) AS avg_rating

FROM ecommerce_customer_data
GROUP BY delivery_bucket;


-- ============================================================
-- Q16. Device Behaviour
-- Compare device types based on number of orders, total revenue,
-- and average order value.
-- ============================================================

SELECT
    Device_Type,
    COUNT(DISTINCT Order_ID) AS number_of_orders,
    SUM(Total_Amount) AS total_revenue,
    SUM(Total_Amount) / COUNT(DISTINCT Order_ID) AS AOV
FROM ecommerce_customer_data
GROUP BY Device_Type;


-- ============================================================
-- Q17. Customer Revenue Ranking
-- Rank customers by total revenue using DENSE_RANK() and identify
-- the top 10 customers.
-- ============================================================

WITH TABLE_1 AS (
    SELECT
        Customer_ID,
        SUM(Total_Amount) AS Revenue,
        DENSE_RANK() OVER (
            ORDER BY SUM(Total_Amount) DESC
        ) AS rnk
    FROM ecommerce_customer_data
    GROUP BY Customer_ID
)
SELECT
    Customer_ID,
    Revenue,
    rnk
FROM TABLE_1
WHERE rnk <= 10;


-- ============================================================
-- Q18. Customer Revenue Contribution
-- Calculate the percentage of total revenue contributed by each
-- customer.
-- ============================================================

WITH TABLE_1 AS (
    SELECT
        Customer_ID,
        SUM(Total_Amount) AS revenue
    FROM ecommerce_customer_data
    GROUP BY Customer_ID
)
SELECT
    Customer_ID,
    revenue,
    revenue / SUM(revenue) OVER () * 100 AS contribution
FROM TABLE_1;


-- ============================================================
-- End of SQL Solutions
-- ============================================================
